#!/usr/bin/make -f

include ../utils/config.mk
objects += tp.o
objects += core/segm.o
objects += core/ordo.o
objects += core/user.o
objects += core/tasks.o
objects += core/paging.o
objects += core/switch.o

INCLUDE += -Iinclude/
include ../utils/rules.mk
